/*
 * Copyright (C) 2024 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v1.0.0
 *
 * lv_conf_custom.h for custom lv_conf.h file
 * example : 
 *     #undef LV_USE_LOG
 *     #define LV_USE_LOG 1
 */

#ifndef LV_CONF_CUSTOM_H
#define LV_CONF_CUSTOM_H

/* code  begin */

#undef LV_USE_FREETYPE
#define LV_USE_FREETYPE 1

/* code end */

#endif  /* LV_CONF_CUSTOM_H */
