/*
 * Copyright (C) 2024 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v1.0.0
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"


void screen_create(ui_manager_t *ui)
{
    screen_t *scr = screen_get(ui);

    if (!ui->auto_del && scr->obj)
        return;

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_AUTO);

    // Init scr->button_1
    scr->button_1 = lv_btn_create(scr->obj);
    lv_obj_t *button_1_label = lv_label_create(scr->button_1);
    lv_label_set_text(button_1_label, "Button");
    lv_obj_align(button_1_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->button_1, 213, 136);
    lv_obj_set_size(scr->button_1, 87, 43);
    lv_obj_add_flag(scr->button_1, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_flag(scr->button_1, LV_OBJ_FLAG_CHECKABLE);

    // Set style of scr->button_1
    lv_obj_set_style_text_font(scr->button_1, montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->button_1, lv_color_hex(0x55ff7f), LV_PART_MAIN | LV_STATE_CHECKED);


}
