/*
 * Copyright (C) 2024 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v1.0.0
 */

#include "ui_objects.h"
#include "ui_init.h"
#include "ui_util.h"
#include "aic_ui.h"
#include "custom/custom.h"

ui_manager_t ui_manager;

lv_font_t *montserratmedium_16;

void ui_init(void)
{
    montserratmedium_16 = ui_font_init(LVGL_FONT_PATH(montserratMedium.ttf), 16);
    if (!montserratmedium_16) {
    	LV_LOG_ERROR("Failed to init montserratmedium_16");
    	return;
    }


    // auto delete screen
    ui_manager_init(&ui_manager, true);

    screen_create(&ui_manager);
    lv_scr_load(screen_get(&ui_manager)->obj);

    // custom code
    custom_init();
}
