/*
 * Copyright (C) 2024 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v1.0.0
 */

#include "lvgl.h"
#include "custom.h"

void custom_init()
{
    /* Add your codes here */
}

